### ISSUE TITLE
jshint.js file origin

### ISSUE THREAD

**Issue by bodorjzsolt** [tchojnacki/FANDOM-Monaco#30]
In 2018 the file jshint.js was added, but I can't find it's source/origin. jshint releases from and before 2018 doesn't contain this file, not in this format anyway. For licensing issues, could you direct me to the source?

**Comment by tchojnacki** [comment]
Hello!

I don't exactly remember as it was 3 years ago, although, according to [commit history](https://github.com/tchojnacki/FANDOM-Monaco/commit/c9542ed80986d7ff583a63f3df33e2a14e3f1c84#diff-81bc52c095e350118867727ac555c181ec0e4b8de06521f704677f7a60cdb5b8L32) it is version 2.9.6 of JSHint, released 2018-07-30 and available at [Cloudflare's cdnjs](https://cdnjs.cloudflare.com/ajax/libs/jshint/2.9.6/jshint.min.js). It seems it had the exact same license as it does to this day (available [here](https://github.com/jshint/jshint/blob/master/LICENSE) and also in FANDOM-Monaco's THIRD-PARTY-NOTICES.md file).

**Comment by bodorjzsolt** [comment]
Thank you for clarifying this.
